apiVersion: eventstreams.ibm.com/v1alpha1
kind: KafkaConnector
metadata:
  name: mq-source-connector #replace - source connector name
  namespace: cp4i #replace - namespace where eventstreams is installed
  labels:
    eventstreams.ibm.com/cluster: es-prod-cluster #replace - name of your kafkaconnectS2I (line 4 of kafkaconnectS2I.yaml)
spec:
  class: com.ibm.eventstreams.connect.mqsource.MQSourceConnector
  tasksMax: 1
  config:
    key.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    value.converter: org.apache.kafka.connect.converters.ByteArrayConverter
    topic: MQ.TOPIC #replace - eventstreams topic name 
    mq.queue.manager: <> #replace - MQ queue manager
    mq.connection.name.list: <hostname>(443) #replace - hostname with port in the parentheses for example, icp.cp4i.ibm.com(443)
    mq.channel.name: <> #replace - channel name
    mq.queue: <> #replace - queue name
    mq.record.builder: com.ibm.eventstreams.connect.mqsource.builders.DefaultRecordBuilder
    mq.ssl.cipher.suite: '*TLS12'  #replace - cipher suite (not cipher specification)
    mq.ssl.truststore.location: /opt/kafka/external-configuration/mq-truststore-cert/client.jks # replace - /opt/kafka/external-configuration/<volumeMount>/<certficateName>
    mq.ssl.truststore.password: passw0rd #replace - password for the certificate
